// ============================================
// JANKAM — STORAGE SERVICE
// Current: localStorage adapter
// Future: swap to Supabase / PostgreSQL with no redesign
// ============================================

const STORAGE_KEYS = {
  COMPLAINTS: 'jankam_complaints',
  MEMBERS: 'jankam_members',
  LEADERSHIP: 'jankam_leadership',
  ANALYTICS: 'jankam_analytics',
} as const;

// ── Census-Grade Seed Data ──
const SEED_COMPLAINTS = [
  {
    id: 'JK-PUN-0021',
    name: 'Rahul S.',
    mobile: '9876543210',
    email: 'rahul.s@gmail.com',
    gender: 'Male',
    age: 28,
    homeState: 'Bihar',
    homeDistrict: 'Patna',
    workState: 'Maharashtra',
    workDistrict: 'Pune',
    industryType: 'Manufacturing',
    workerType: 'Contract Worker',
    educationLevel: 'Secondary',
    preferredLanguage: 'Hindi',
    companyName: 'Bajaj Assembly Plant',
    employeeId: 'BAJ-9021',
    complaintType: 'Overtime Non-Payment',
    description: 'Rahul, an industrial assembler, was forced to work 10-hour shifts daily for 6 months without any overtime compensation. JanKam verified his log cards and drafted a formal legal inquiry, leading to immediate settlement.',
    priorityLevel: 'Medium',
    documentType: 'Salary Slip',
    status: 'resolved',
    createdAt: '2026-05-20T10:00:00.000Z',
    employerName: 'Bajaj Assembly Plant (Manager)',
    employerMobile: '9812345678',
    employerEmail: 'ops@bajajassembly.com',
    companyAddress: 'Plot No. 42, MIDC Chakan, Pune, MH',
    workSiteAddress: 'Chakan Plant Assembly Line 2, Pune',
    supervisorName: 'Mr. Shinde',
    supervisorMobile: '9823456789',
    hrMobile: '9834567890',
    hrEmail: 'hr@bajajassembly.com',
    incidentDate: '2026-05-18',
    complaintAgainst: 'Employer',
    approxFinancialLoss: '₹18,000',
    witnessName: 'Sunil Kumar',
    witnessMobile: '9845678901',
    witnessDesignation: 'Co-assembler',
    evidenceNotes: 'Log card sheets and monthly bank statements showing regular pay without double rate OT.',
    workerMobileVerified: true,
    lastNotificationSent: '2026-05-21T12:00:00.000Z',
    notificationType: 'WhatsApp',
    internalNotes: 'Employer contacted. Dues cleared via direct bank transfer after receiving JanKam official legal inquiry.',
    publicUpdate: 'Recovery of ₹18,000 completed. Case closed successfully.',
    currentStage: 'resolved',
    assignedVolunteer: 'Suresh Mane',
    assignedDistrictTeam: 'Pune District Desk',
    assignedOfficer: 'Pankaj Dhole'
  },
  {
    id: 'JK-NAS-0045',
    name: 'Amit P.',
    mobile: '9865432109',
    email: 'amit.p@gmail.com',
    gender: 'Male',
    age: 32,
    homeState: 'Uttar Pradesh',
    homeDistrict: 'Lucknow',
    workState: 'Maharashtra',
    workDistrict: 'Nashik',
    industryType: 'Textile',
    workerType: 'Permanent Employee',
    educationLevel: 'Higher Secondary',
    preferredLanguage: 'Marathi',
    companyName: 'Nashik Cotton Mills',
    employeeId: 'NCM-1045',
    complaintType: 'PF Issue',
    description: 'Amit found that 12% was regularly deducted from his wage slips, but the EPFO database showed zero deposits for 8 months. JanKam filed a non-deposit complaint, compelling the company to clear all outstanding PF arrears.',
    priorityLevel: 'Medium',
    documentType: 'PF Statement',
    status: 'resolved',
    createdAt: '2026-05-18T14:30:00.000Z',
    employerName: 'Nashik Cotton Mills Ltd.',
    employerMobile: '9898765432',
    employerEmail: 'contact@nashikcotton.com',
    companyAddress: 'Sinnar Industrial Estate, Nashik, MH',
    workSiteAddress: 'Spinning Department Block B, Nashik',
    supervisorName: 'Karan Patil',
    incidentDate: '2026-05-10',
    complaintAgainst: 'Employer',
    approxFinancialLoss: '₹22,000 (PF Arrears)',
    evidenceNotes: 'EPFO passbook showing deduction without credit.',
    workerMobileVerified: true,
    lastNotificationSent: '2026-05-19T11:00:00.000Z',
    notificationType: 'SMS',
    internalNotes: 'EPFO complaint registered. Employer accepted liability and deposited outstanding PF dues.',
    publicUpdate: 'Outstanding PF dues cleared by employer. Verification done.',
    currentStage: 'resolved',
    assignedVolunteer: 'Snehal Shinde',
    assignedDistrictTeam: 'Nashik District Desk',
    assignedOfficer: 'Pradeep Deshmukh'
  },
  {
    id: 'JK-THA-0089',
    name: 'Suman K.',
    mobile: '9765432198',
    email: 'suman.k@gmail.com',
    gender: 'Female',
    age: 29,
    homeState: 'Maharashtra',
    homeDistrict: 'Pune',
    workState: 'Maharashtra',
    workDistrict: 'Thane',
    industryType: 'Warehouse',
    workerType: 'Permanent Employee',
    educationLevel: 'Graduate',
    preferredLanguage: 'English',
    companyName: 'Flipkart Logistics Hub',
    employeeId: 'FLIP-8921',
    complaintType: 'Leave Issue',
    description: 'Suman was threatened with immediate termination after requesting maternity leave. JanKam intervened, presenting statutory warnings under the Maternity Benefit Act, securing both her position and full salary benefits.',
    priorityLevel: 'Medium',
    documentType: 'Appointment Letter',
    status: 'resolved',
    createdAt: '2026-05-15T09:15:00.000Z',
    employerName: 'Instakart Services (Flipkart)',
    employerMobile: '9888877777',
    companyAddress: 'Bhiwandi Logistics Hub, Thane, MH',
    workSiteAddress: 'Bhiwandi Warehouse Cluster 3, Thane',
    incidentDate: '2026-05-12',
    complaintAgainst: 'Company Management',
    workerMobileVerified: true,
    lastNotificationSent: '2026-05-16T15:30:00.000Z',
    notificationType: 'Email',
    internalNotes: 'Maternity Benefit Act statutory notice sent. Management agreed to 26 weeks paid leave.',
    publicUpdate: 'Maternity leave approved with full pay protection.',
    currentStage: 'resolved',
    assignedVolunteer: 'Gopal Das',
    assignedDistrictTeam: 'Thane District Desk',
    assignedOfficer: 'Anjali Thorat'
  },
  {
    id: 'JK-MUM-0112',
    name: 'Meera D.',
    mobile: '9654321987',
    email: 'meera.d@gmail.com',
    gender: 'Female',
    age: 30,
    homeState: 'Karnataka',
    homeDistrict: 'Mysuru',
    workState: 'Maharashtra',
    workDistrict: 'Mumbai City',
    industryType: 'Hotel',
    workerType: 'Gig Worker',
    educationLevel: 'Graduate',
    preferredLanguage: 'English',
    companyName: 'Taj Catering Services',
    employeeId: 'TAJ-1123',
    complaintType: 'Women Safety',
    description: 'Meera faced a hostile working environment with no safety officer on site. JanKam filed an official POSH non-compliance action, forcing the establishment to set up a fully functional Internal Complaints Committee.',
    priorityLevel: 'High',
    documentType: 'Complaint Evidence',
    status: 'resolved',
    createdAt: '2026-05-12T11:00:00.000Z',
    employerName: 'Taj Catering Services Pvt. Ltd.',
    companyAddress: 'Gateway Vista Hotel Compound, Mumbai',
    workSiteAddress: 'Main Kitchen & Catering Zone, Colaba, Mumbai',
    incidentDate: '2026-05-08',
    complaintAgainst: 'Company Management',
    workerMobileVerified: true,
    lastNotificationSent: '2026-05-13T10:00:00.000Z',
    notificationType: 'WhatsApp',
    internalNotes: 'POSH non-compliance notice sent. ICC established with external legal experts.',
    publicUpdate: 'Internal Complaints Committee established and POSH guidelines displayed.',
    currentStage: 'resolved',
    assignedVolunteer: 'Nisha Dubey',
    assignedDistrictTeam: 'Mumbai District Desk',
    assignedOfficer: 'Vandana Salvi'
  },
  {
    id: 'JK-KOL-0067',
    name: 'Ganesh G.',
    mobile: '9543219876',
    email: 'ganesh.g@gmail.com',
    gender: 'Male',
    age: 24,
    homeState: 'Maharashtra',
    homeDistrict: 'Kolhapur',
    workState: 'Maharashtra',
    workDistrict: 'Kolhapur',
    industryType: 'Engineering',
    workerType: 'Trainee',
    educationLevel: 'Diploma',
    preferredLanguage: 'Marathi',
    companyName: 'Kolhapur Steel Foundry',
    employeeId: 'KSF-0067',
    complaintType: 'Salary Delay',
    description: 'Ganesh was paid ₹8,500 monthly instead of the statutory unskilled minimum wage of ₹13,200. JanKam filed a wage recovery petition, securing the legal wage correction and clearance of past underpaid arrears.',
    priorityLevel: 'Medium',
    documentType: 'Salary Slip',
    status: 'resolved',
    createdAt: '2026-05-10T16:45:00.000Z',
    employerName: 'Kolhapur Steel & Iron Foundry',
    companyAddress: 'Shiroli MIDC, Kolhapur, MH',
    workSiteAddress: 'Foundry Floor Section A, Shiroli, Kolhapur',
    incidentDate: '2026-05-05',
    complaintAgainst: 'Employer',
    approxFinancialLoss: '₹4,700/month',
    workerMobileVerified: true,
    notificationType: 'SMS',
    internalNotes: 'Wage petition filed under Minimum Wages Act. Employer matched statutory slab.',
    publicUpdate: 'Minimum wage adjustment implemented and difference paid.',
    currentStage: 'resolved',
    assignedVolunteer: 'Suresh Mane',
    assignedDistrictTeam: 'Kolhapur District Desk',
    assignedOfficer: 'Devendra Patil'
  },
  {
    id: 'JK-MUM-0125',
    name: 'Ramesh K.',
    mobile: '9432198765',
    email: 'ramesh.k@gmail.com',
    gender: 'Male',
    age: 41,
    homeState: 'Bihar',
    homeDistrict: 'Gaya',
    workState: 'Maharashtra',
    workDistrict: 'Mumbai Suburban',
    industryType: 'Construction',
    workerType: 'Daily Wage Worker',
    educationLevel: 'Primary',
    preferredLanguage: 'Hindi',
    companyName: 'L&T Construction Site',
    employeeId: 'LT-1250',
    complaintType: 'Salary Deduction',
    description: 'Ramesh faced illegal salary deductions for safety tools that are legally mandated to be provided for free by the builder.',
    priorityLevel: 'Medium',
    documentType: 'Identity Proof',
    status: 'submitted',
    createdAt: '2026-05-29T10:00:00.000Z',
    employerName: 'L&T Infra Projects Metro Site',
    companyAddress: 'L&T House, Ballard Estate, Mumbai',
    workSiteAddress: 'Andheri Metro Station construction yard, Mumbai',
    incidentDate: '2026-05-28',
    complaintAgainst: 'Contractor',
    approxFinancialLoss: '₹1,500',
    workerMobileVerified: true,
    notificationType: 'WhatsApp',
    internalNotes: 'Intake successful. Verifying contractor wage rolls.',
    publicUpdate: 'Complaint registered and assigned to district representative.',
    currentStage: 'submitted',
    assignedVolunteer: 'Nisha Dubey',
    assignedDistrictTeam: 'Mumbai District Desk',
    assignedOfficer: 'Sanjay Deshmukh'
  },
  {
    id: 'JK-PUN-0130',
    name: 'Kiran S.',
    mobile: '9321987654',
    email: 'kiran.s@gmail.com',
    gender: 'Female',
    age: 26,
    homeState: 'Jharkhand',
    homeDistrict: 'Ranchi',
    workState: 'Maharashtra',
    workDistrict: 'Pune',
    industryType: 'BPO',
    workerType: 'Contract Worker',
    educationLevel: 'Graduate',
    preferredLanguage: 'English',
    companyName: 'Wipro Tech Center',
    employeeId: 'WIP-1300',
    complaintType: 'Illegal Termination',
    description: 'Kiran was terminated immediately without notice or full and final settlement after requesting sick leaves.',
    priorityLevel: 'High',
    documentType: 'Appointment Letter',
    status: 'under_review',
    createdAt: '2026-05-30T01:20:00.000Z',
    employerName: 'Wipro Tech Campus Chinchwad',
    companyAddress: 'Phase 2, Hinjewadi IT Park, Pune',
    workSiteAddress: 'Operations Block 4, Hinjewadi, Pune',
    incidentDate: '2026-05-25',
    complaintAgainst: 'HR Department',
    approxFinancialLoss: '₹45,000 (1 month salary)',
    workerMobileVerified: true,
    notificationType: 'WhatsApp',
    internalNotes: 'Workplace dispute under review. Scheduled conciliation call with HR lead.',
    publicUpdate: 'Review in progress. Legal review of termination letter completed.',
    currentStage: 'under_review',
    assignedVolunteer: 'Suresh Mane',
    assignedDistrictTeam: 'Pune District Desk',
    assignedOfficer: 'Adv. Shruti Kulkarni'
  }
];

const SEED_MEMBERS = [
  {
    id: 'JKM-PUN-0001',
    name: 'Vijay Patil',
    mobile: '9870123456',
    email: 'vijay.patil@gmail.com',
    gender: 'Male',
    age: 32,
    homeState: 'Maharashtra',
    homeDistrict: 'Kolhapur',
    workState: 'Maharashtra',
    workDistrict: 'Pune',
    industryType: 'Automobile',
    workerType: 'Permanent Employee',
    educationLevel: 'Diploma',
    preferredLanguage: 'Marathi',
    companyName: 'Tata Motors',
    occupation: 'Assembly Technician',
    experience: '6',
    joinDate: '2026-04-10',
    status: 'active',
    createdAt: '2026-04-10T10:00:00.000Z'
  },
  {
    id: 'JKM-THA-0002',
    name: 'Sunita Shinde',
    mobile: '9860123457',
    email: 'sunita.s@gmail.com',
    gender: 'Female',
    age: 28,
    homeState: 'Maharashtra',
    homeDistrict: 'Satara',
    workState: 'Maharashtra',
    workDistrict: 'Thane',
    industryType: 'Hospital',
    workerType: 'Permanent Employee',
    educationLevel: 'Graduate',
    preferredLanguage: 'Marathi',
    companyName: 'Jupiter Hospital',
    occupation: 'Staff Nurse',
    experience: '4',
    joinDate: '2026-04-15',
    status: 'active',
    createdAt: '2026-04-15T12:00:00.000Z'
  },
  {
    id: 'JKM-MUM-0003',
    name: 'Arjun Singh',
    mobile: '9850123458',
    email: 'arjun.singh@gmail.com',
    gender: 'Male',
    age: 35,
    homeState: 'Uttar Pradesh',
    homeDistrict: 'Varanasi',
    workState: 'Maharashtra',
    workDistrict: 'Mumbai City',
    industryType: 'Security',
    workerType: 'Contract Worker',
    educationLevel: 'Secondary',
    preferredLanguage: 'Hindi',
    companyName: 'G4S Security',
    occupation: 'Security Supervisor',
    experience: '8',
    joinDate: '2026-04-20',
    status: 'active',
    createdAt: '2026-04-20T14:00:00.000Z'
  },
  {
    id: 'JKM-NAS-0004',
    name: 'Maya Patil',
    mobile: '9840123459',
    email: 'maya.patil@gmail.com',
    gender: 'Female',
    age: 26,
    homeState: 'Maharashtra',
    homeDistrict: 'Jalgaon',
    workState: 'Maharashtra',
    workDistrict: 'Nashik',
    industryType: 'Agriculture',
    workerType: 'Daily Wage Worker',
    educationLevel: 'Primary',
    preferredLanguage: 'Marathi',
    companyName: 'Sahyadri Farms',
    occupation: 'Packer',
    experience: '3',
    joinDate: '2026-04-22',
    status: 'active',
    createdAt: '2026-04-22T11:00:00.000Z'
  },
  {
    id: 'JKM-PUN-0005',
    name: 'Deepak Kumar',
    mobile: '9830123460',
    email: 'deepak.k@gmail.com',
    gender: 'Male',
    age: 29,
    homeState: 'Bihar',
    homeDistrict: 'Gaya',
    workState: 'Maharashtra',
    workDistrict: 'Pune',
    industryType: 'Logistics',
    workerType: 'Gig Worker',
    educationLevel: 'Higher Secondary',
    preferredLanguage: 'Hindi',
    companyName: 'Delhivery Warehouse',
    occupation: 'Delivery Executive',
    experience: '2',
    joinDate: '2026-04-28',
    status: 'active',
    createdAt: '2026-04-28T09:30:00.000Z'
  },
  {
    id: 'JKM-SOL-0006',
    name: 'Ramdas Kamble',
    mobile: '9820123461',
    email: 'ramdas.k@gmail.com',
    gender: 'Male',
    age: 42,
    homeState: 'Maharashtra',
    homeDistrict: 'Solapur',
    workState: 'Maharashtra',
    workDistrict: 'Solapur',
    industryType: 'Textile',
    workerType: 'Permanent Employee',
    educationLevel: 'Secondary',
    preferredLanguage: 'Marathi',
    companyName: 'Solapur Handloom Co',
    occupation: 'Weaving operator',
    experience: '15',
    joinDate: '2026-05-02',
    status: 'active',
    createdAt: '2026-05-02T16:00:00.000Z'
  }
];

const SEED_VOLUNTEERS = [
  {
    id: 'JKL-001',
    name: 'Suresh Mane',
    mobile: '9871112233',
    email: 'suresh.mane@gmail.com',
    state: 'Maharashtra',
    district: 'Pune',
    industryType: 'Manufacturing',
    workerType: 'Permanent Employee',
    educationLevel: 'Graduate',
    preferredLanguage: 'Marathi',
    skills: ['Labour Rights Awareness', 'Legal Support', 'Worker Counseling'],
    emergencyName: 'Asha Mane',
    emergencyMobile: '9871112244',
    status: 'active',
    createdAt: '2026-04-01T10:00:00.000Z'
  },
  {
    id: 'JKL-002',
    name: 'Nisha Dubey',
    mobile: '9861112233',
    email: 'nisha.dubey@gmail.com',
    state: 'Maharashtra',
    district: 'Mumbai City',
    industryType: 'Education',
    workerType: 'Trainee',
    educationLevel: 'Post Graduate',
    preferredLanguage: 'Hindi',
    skills: ['Social Media', 'Data Entry', 'Digital Marketing'],
    emergencyName: 'Rajesh Dubey',
    emergencyMobile: '9861112244',
    status: 'active',
    createdAt: '2026-04-05T12:00:00.000Z'
  },
  {
    id: 'JKL-003',
    name: 'Gopal Das',
    mobile: '9851112233',
    email: 'gopal.das@gmail.com',
    state: 'Maharashtra',
    district: 'Thane',
    industryType: 'Construction',
    workerType: 'Contract Worker',
    educationLevel: 'Secondary',
    preferredLanguage: 'Hindi',
    skills: ['Community Outreach', 'Event Coordination'],
    emergencyName: 'Mohan Das',
    emergencyMobile: '9851112244',
    status: 'active',
    createdAt: '2026-04-10T14:00:00.000Z'
  },
  {
    id: 'JKL-004',
    name: 'Snehal Shinde',
    mobile: '9841112233',
    email: 'snehal.s@gmail.com',
    state: 'Maharashtra',
    district: 'Nashik',
    industryType: 'Agriculture',
    workerType: 'Permanent Employee',
    educationLevel: 'Graduate',
    preferredLanguage: 'Marathi',
    skills: ['Training', 'Labour Rights Awareness'],
    emergencyName: 'Sanjay Shinde',
    emergencyMobile: '9841112244',
    status: 'active',
    createdAt: '2026-04-15T09:00:00.000Z'
  }
];

export const storageService = {
  get: <T>(key: string): T[] => {
    try {
      const raw = localStorage.getItem(key);
      if (raw) return JSON.parse(raw) as T[];
      
      // Seed if empty
      if (key === STORAGE_KEYS.COMPLAINTS) {
        localStorage.setItem(key, JSON.stringify(SEED_COMPLAINTS));
        return SEED_COMPLAINTS as unknown as T[];
      }
      if (key === STORAGE_KEYS.MEMBERS) {
        localStorage.setItem(key, JSON.stringify(SEED_MEMBERS));
        return SEED_MEMBERS as unknown as T[];
      }
      if (key === STORAGE_KEYS.LEADERSHIP) {
        localStorage.setItem(key, JSON.stringify(SEED_VOLUNTEERS));
        return SEED_VOLUNTEERS as unknown as T[];
      }
      return [];
    } catch {
      return [];
    }
  },

  set: <T>(key: string, data: T[]): void => {
    try {
      localStorage.setItem(key, JSON.stringify(data));
    } catch {
      console.warn('Storage write failed');
    }
  },

  append: <T>(key: string, item: T): void => {
    const existing = storageService.get<T>(key);
    existing.push(item);
    storageService.set(key, existing);
  },

  count: (key: string): number => {
    return storageService.get(key).length;
  },
};

export { STORAGE_KEYS };
